###########################################################
# GCC template makefile
###########################################################


DRIVER_SOURCES = 
DRIVER_SOURCES += misc.c
DRIVER_SOURCES += stm32f10x_adc.c
DRIVER_SOURCES += stm32f10x_bkp.c
DRIVER_SOURCES += stm32f10x_can.c
DRIVER_SOURCES += stm32f10x_crc.c
DRIVER_SOURCES += stm32f10x_dac.c
DRIVER_SOURCES += stm32f10x_dbgmcu.c
DRIVER_SOURCES += stm32f10x_dma.c
DRIVER_SOURCES += stm32f10x_exti.c
DRIVER_SOURCES += stm32f10x_flash.c
DRIVER_SOURCES += stm32f10x_fsmc.c
DRIVER_SOURCES += stm32f10x_gpio.c
DRIVER_SOURCES += stm32f10x_i2c.c
DRIVER_SOURCES += stm32f10x_iwdg.c
DRIVER_SOURCES += stm32f10x_pwr.c
DRIVER_SOURCES += stm32f10x_rcc.c
DRIVER_SOURCES += stm32f10x_rtc.c
DRIVER_SOURCES += stm32f10x_sdio.c
DRIVER_SOURCES += stm32f10x_spi.c
DRIVER_SOURCES += stm32f10x_tim.c
DRIVER_SOURCES += stm32f10x_usart.c
DRIVER_SOURCES += stm32f10x_wwdg.c

EXTRAINCDIRS += $(TOP)/driver/STM32F10x_StdPeriph_Driver/Inc

C_SOURCES += $(DRIVER_SOURCES)