###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_DAC_SING_PULSE :=
  	EDU_BOARD_DAC_SING_PULSE += stm32f4xx_hal_msp.c
  	EDU_BOARD_DAC_SING_PULSE += stm32f4xx_it.c
  	EDU_BOARD_DAC_SING_PULSE += syscalls.c
  	EDU_BOARD_DAC_SING_PULSE += sysmem.c
  	EDU_BOARD_DAC_SING_PULSE += system_stm32f4xx.c
  	EDU_BOARD_DAC_SING_PULSE += gpio.c
  	EDU_BOARD_DAC_SING_PULSE += tim.c
  	EDU_BOARD_DAC_SING_PULSE += adc.c
  	EDU_BOARD_DAC_SING_PULSE += dma.c
  	EDU_BOARD_DAC_SING_PULSE += dac.c
  	EDU_BOARD_DAC_SING_PULSE += usart.c
  	EDU_BOARD_DAC_SING_PULSE += CLCD.c
  	EDU_BOARD_DAC_SING_PULSE += 7SEG.c
    EDU_BOARD_DAC_SING_PULSE += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/15_DAC/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_DAC_SING_PULSE)
