###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_UART :=
  	EDU_BOARD_SIMPLE_UART += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_UART += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_UART += syscalls.c
  	EDU_BOARD_SIMPLE_UART += sysmem.c
  	EDU_BOARD_SIMPLE_UART += system_stm32f4xx.c
    EDU_BOARD_SIMPLE_UART += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/02_simple_uart/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_UART)
