###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_TIM_TIMER :=
  	EDU_BOARD_SIMPLE_TIM_TIMER += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_TIM_TIMER += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_TIM_TIMER += syscalls.c
  	EDU_BOARD_SIMPLE_TIM_TIMER += sysmem.c
  	EDU_BOARD_SIMPLE_TIM_TIMER += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_TIM_TIMER += CLCD.c
    EDU_BOARD_SIMPLE_TIM_TIMER += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/06_TIM_Timer/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_TIM_TIMER)
