###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_GPIO :=
  	EDU_BOARD_SIMPLE_GPIO += gpio.c
  	EDU_BOARD_SIMPLE_GPIO += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_GPIO += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_GPIO += syscalls.c
  	EDU_BOARD_SIMPLE_GPIO += sysmem.c
  	EDU_BOARD_SIMPLE_GPIO += system_stm32f4xx.c
    EDU_BOARD_SIMPLE_GPIO += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/01_simple_gpio/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_GPIO)
