###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE :=
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += syscalls.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += sysmem.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += gpio.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += tim.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += usart.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += CLCD.c
  	EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += 7SEG.c
    EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/13_PWM_repeat_Cycle/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_PWM_REPEAT_CYCLE)
