###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SPI_VS1003_SOURCE :=
  	EDU_BOARD_SPI_VS1003_SOURCE += stm32f4xx_hal_msp.c
  	EDU_BOARD_SPI_VS1003_SOURCE += stm32f4xx_it.c
  	EDU_BOARD_SPI_VS1003_SOURCE += syscalls.c
  	EDU_BOARD_SPI_VS1003_SOURCE += sysmem.c
  	EDU_BOARD_SPI_VS1003_SOURCE += system_stm32f4xx.c
  	EDU_BOARD_SPI_VS1003_SOURCE += gpio.c
  	EDU_BOARD_SPI_VS1003_SOURCE += tim.c
  	EDU_BOARD_SPI_VS1003_SOURCE += adc.c
  	EDU_BOARD_SPI_VS1003_SOURCE += dma.c
  	EDU_BOARD_SPI_VS1003_SOURCE += usart.c
  	EDU_BOARD_SPI_VS1003_SOURCE += i2c.c
  	EDU_BOARD_SPI_VS1003_SOURCE += spi.c
  	EDU_BOARD_SPI_VS1003_SOURCE += CLCD.c
  	EDU_BOARD_SPI_VS1003_SOURCE += 7SEG.c
  	EDU_BOARD_SPI_VS1003_SOURCE += VS1003.c
    EDU_BOARD_SPI_VS1003_SOURCE += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/17_SPI_VS1003/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SPI_VS1003_SOURCE)
