###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR :=
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += syscalls.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += sysmem.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += gpio.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += tim.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += usart.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += CLCD.c
  	EDU_BOARD_SIMPLE_PWM_DC_MOTOR += 7SEG.c
    EDU_BOARD_SIMPLE_PWM_DC_MOTOR += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/12_PWM_DC_Motor/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_PWM_DC_MOTOR)
