###########################################################
# GCC template makefile
###########################################################

CORE_SOURCES = 
CORE_SOURCES += core_cm3.c
CORE_SOURCES += system_stm32f10x.c


C_SOURCES += $(CORE_SOURCES)
