###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_ADC_WITH_DMA :=
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += syscalls.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += sysmem.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += gpio.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += tim.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += adc.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += dma.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += usart.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += CLCD.c
  	EDU_BOARD_SIMPLE_ADC_WITH_DMA += 7SEG.c
    EDU_BOARD_SIMPLE_ADC_WITH_DMA += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/14_ADC_with_DMA/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_ADC_WITH_DMA)
