###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER :=
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += syscalls.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += sysmem.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += gpio.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += tim.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += usart.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += CLCD.c
  	EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += 7SEG.c
    EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/11_PWM_passive_buzzer/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_PWM_PASSIVE_BUZZER)
