###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SD_CARD_MP3_SOURCE :=
  	EDU_BOARD_SD_CARD_MP3_SOURCE += stm32f4xx_hal_msp.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += stm32f4xx_it.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += syscalls.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += sysmem.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += system_stm32f4xx.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += gpio.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += tim.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += adc.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += dma.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += usart.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += i2c.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += spi.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += sdio.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += CLCD.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += 7SEG.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += VS1003.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += fatfs.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += bsp_driver_sd.c
  	EDU_BOARD_SD_CARD_MP3_SOURCE += sd_diskio.c
    EDU_BOARD_SD_CARD_MP3_SOURCE += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/19_SD_Card_FatFS_MP3/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SD_CARD_MP3_SOURCE)
