###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_I2C_EEPROM :=
  	EDU_BOARD_I2C_EEPROM += stm32f4xx_hal_msp.c
  	EDU_BOARD_I2C_EEPROM += stm32f4xx_it.c
  	EDU_BOARD_I2C_EEPROM += syscalls.c
  	EDU_BOARD_I2C_EEPROM += sysmem.c
  	EDU_BOARD_I2C_EEPROM += system_stm32f4xx.c
  	EDU_BOARD_I2C_EEPROM += gpio.c
  	EDU_BOARD_I2C_EEPROM += tim.c
  	EDU_BOARD_I2C_EEPROM += adc.c
  	EDU_BOARD_I2C_EEPROM += dma.c
  	EDU_BOARD_I2C_EEPROM += dac.c
  	EDU_BOARD_I2C_EEPROM += usart.c
  	EDU_BOARD_I2C_EEPROM += i2c.c
  	EDU_BOARD_I2C_EEPROM += CLCD.c
  	EDU_BOARD_I2C_EEPROM += 7SEG.c
    EDU_BOARD_I2C_EEPROM += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/16_I2C/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_I2C_EEPROM)
