###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE :=
  	EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE += syscalls.c
  	EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE += sysmem.c
  	EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE += CLCD.c
    EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/05_character_LCD/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_CHARACTER_LCD_WRITE)
