###########################################################
# GCC template makefile
###########################################################


DRIVER_SOURCES = 
DRIVER_SOURCES += misc.c
DRIVER_SOURCES += stm32f4xx_adc.c
DRIVER_SOURCES += stm32f4xx_can.c
#DRIVER_SOURCES += stm32f4xx_cec.c
DRIVER_SOURCES += stm32f4xx_crc.c
DRIVER_SOURCES += stm32f4xx_cryp.c
DRIVER_SOURCES += stm32f4xx_cryp_aes.c
DRIVER_SOURCES += stm32f4xx_cryp_des.c
DRIVER_SOURCES += stm32f4xx_cryp_tdes.c
DRIVER_SOURCES += stm32f4xx_dac.c
DRIVER_SOURCES += stm32f4xx_dbgmcu.c
DRIVER_SOURCES += stm32f4xx_dcmi.c
#DRIVER_SOURCES += stm32f4xx_dfsdm.c
DRIVER_SOURCES += stm32f4xx_dma.c
#DRIVER_SOURCES += stm32f4xx_dma2d.c
#DRIVER_SOURCES += stm32f4xx_dsi.c
DRIVER_SOURCES += stm32f4xx_exti.c
DRIVER_SOURCES += stm32f4xx_flash.c
#DRIVER_SOURCES += stm32f4xx_flash_ramfunc.c
#DRIVER_SOURCES += stm32f4xx_fmc.c
#DRIVER_SOURCES += stm32f4xx_fmpi2c.c
DRIVER_SOURCES += stm32f4xx_fsmc.c
DRIVER_SOURCES += stm32f4xx_gpio.c
DRIVER_SOURCES += stm32f4xx_hash.c
#DRIVER_SOURCES += stm32f4xx_hash_dm5.c
DRIVER_SOURCES += stm32f4xx_hash_sha1.c
DRIVER_SOURCES += stm32f4xx_i2c.c
DRIVER_SOURCES += stm32f4xx_iwdg.c
#DRIVER_SOURCES += stm32f4xx_lptim.c
#DRIVER_SOURCES += stm32f4xx_ltdc.c
DRIVER_SOURCES += stm32f4xx_pwr.c
#DRIVER_SOURCES += stm32f4xx_qspi.c
DRIVER_SOURCES += stm32f4xx_rcc.c
DRIVER_SOURCES += stm32f4xx_rng.c
DRIVER_SOURCES += stm32f4xx_rtc.c
#DRIVER_SOURCES += stm32f4xx_sai.c
DRIVER_SOURCES += stm32f4xx_sdio.c
#DRIVER_SOURCES += stm32f4xx_spdifrx.c
DRIVER_SOURCES += stm32f4xx_spi.c
DRIVER_SOURCES += stm32f4xx_syscfg.c
DRIVER_SOURCES += stm32f4xx_tim.c
DRIVER_SOURCES += stm32f4xx_usart.c
DRIVER_SOURCES += stm32f4xx_wwdg.c

EXTRAINCDIRS += $(TOP)/driver/STM32F4xx_StdPeriph_Driver/Inc

C_SOURCES += $(DRIVER_SOURCES)