###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_EXTI_INPUT :=
  	EDU_BOARD_SIMPLE_EXTI_INPUT += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_EXTI_INPUT += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_EXTI_INPUT += syscalls.c
  	EDU_BOARD_SIMPLE_EXTI_INPUT += sysmem.c
  	EDU_BOARD_SIMPLE_EXTI_INPUT += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_EXTI_INPUT += CLCD.c
  	EDU_BOARD_SIMPLE_EXTI_INPUT += 7SEG.c
    EDU_BOARD_SIMPLE_EXTI_INPUT += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/08_EXTI_InputInterrupt/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_EXTI_INPUT)
