###########################################################
# GCC template makefile
###########################################################

CORE_SOURCES =
CORE_SOURCES += system_stm32f4xx.c

C_SOURCES += $(CORE_SOURCES)


EXTRAINCDIRS += $(TOP)/CMSIS/Core/CM4/Inc
EXTRAINCDIRS += $(TOP)/CMSIS/Core/CM4/Core
