###########################################################
# GCC template makefile
###########################################################

DEFAULT_ASMSOURCES = startup_stm32f407xx.s

ASM_SOURCES += $(DEFAULT_ASMSOURCES)