###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_UART_PRINTF :=
  	EDU_BOARD_SIMPLE_UART_PRINTF += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_UART_PRINTF += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_UART_PRINTF += syscalls.c
  	EDU_BOARD_SIMPLE_UART_PRINTF += sysmem.c
  	EDU_BOARD_SIMPLE_UART_PRINTF += system_stm32f4xx.c
    EDU_BOARD_SIMPLE_UART_PRINTF += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/03_uart_printf/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_UART_PRINTF)
