###########################################################
# GCC template makefile
###########################################################


SUB_ARCH :=
SUB_ARCH += cubeMXstudy

SUB_ARCH := $(addprefix $(TOP)/StudyCode/M-HIVE-EduBoard/, $(SUB_ARCH))

sinclude $(addsuffix /Makefile, $(SUB_ARCH))