###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG :=
  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG += syscalls.c
  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG += sysmem.c
  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG += CLCD.c
  	EDU_BOARD_SIMPLE_TIM_TIMER_SEG += 7SEG.c
    EDU_BOARD_SIMPLE_TIM_TIMER_SEG += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/07_TIM_Timer_SEG/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_TIM_TIMER_SEG)
