###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SD_CARD_SOURCE :=
  	EDU_BOARD_SD_CARD_SOURCE += stm32f4xx_hal_msp.c
  	EDU_BOARD_SD_CARD_SOURCE += stm32f4xx_it.c
  	EDU_BOARD_SD_CARD_SOURCE += syscalls.c
  	EDU_BOARD_SD_CARD_SOURCE += sysmem.c
  	EDU_BOARD_SD_CARD_SOURCE += system_stm32f4xx.c
  	EDU_BOARD_SD_CARD_SOURCE += gpio.c
  	EDU_BOARD_SD_CARD_SOURCE += tim.c
  	EDU_BOARD_SD_CARD_SOURCE += adc.c
  	EDU_BOARD_SD_CARD_SOURCE += dma.c
  	EDU_BOARD_SD_CARD_SOURCE += usart.c
  	EDU_BOARD_SD_CARD_SOURCE += i2c.c
  	EDU_BOARD_SD_CARD_SOURCE += spi.c
  	EDU_BOARD_SD_CARD_SOURCE += sdio.c
  	EDU_BOARD_SD_CARD_SOURCE += CLCD.c
  	EDU_BOARD_SD_CARD_SOURCE += 7SEG.c
  	EDU_BOARD_SD_CARD_SOURCE += VS1003.c
  	EDU_BOARD_SD_CARD_SOURCE += fatfs.c
  	EDU_BOARD_SD_CARD_SOURCE += bsp_driver_sd.c
  	EDU_BOARD_SD_CARD_SOURCE += sd_diskio.c
    EDU_BOARD_SD_CARD_SOURCE += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/18_SD_Card_FatFs/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SD_CARD_SOURCE)
