###########################################################
# GCC template makefile
###########################################################

DEFAULT_ASMSOURCES = startup_stm32f103xb.s

ASM_SOURCES += $(DEFAULT_ASMSOURCES)