###########################################################
# GCC template makefile
###########################################################


DRIVER_SOURCES = 
DRIVER_SOURCES += stm32f1xx_hal_adc_ex.c
DRIVER_SOURCES += stm32f1xx_hal_adc.c
DRIVER_SOURCES += stm32f1xx_hal_can.c
DRIVER_SOURCES += stm32f1xx_hal_cec.c
DRIVER_SOURCES += stm32f1xx_hal_cortex.c
DRIVER_SOURCES += stm32f1xx_hal_crc.c
DRIVER_SOURCES += stm32f1xx_hal_dac_ex.c
DRIVER_SOURCES += stm32f1xx_hal_dma.c
DRIVER_SOURCES += stm32f1xx_hal_eth.c
DRIVER_SOURCES += stm32f1xx_hal_flash_ex.c
DRIVER_SOURCES += stm32f1xx_hal_flash.c
DRIVER_SOURCES += stm32f1xx_hal_gpio_ex.c
DRIVER_SOURCES += stm32f1xx_hal_gpio.c
DRIVER_SOURCES += stm32f1xx_hal_hcd.c
DRIVER_SOURCES += stm32f1xx_hal_i2c.c
DRIVER_SOURCES += stm32f1xx_hal_i2s.c
DRIVER_SOURCES += stm32f1xx_hal_irda.c
DRIVER_SOURCES += stm32f1xx_hal_iwdg.c
DRIVER_SOURCES += stm32f1xx_hal_mmc.c
DRIVER_SOURCES += stm32f1xx_hal_msp_template.c
DRIVER_SOURCES += stm32f1xx_hal_nand.c
DRIVER_SOURCES += stm32f1xx_hal_nor.c
DRIVER_SOURCES += stm32f1xx_hal_pccard.c
DRIVER_SOURCES += stm32f1xx_hal_pcd_ex.c
DRIVER_SOURCES += stm32f1xx_hal_pcd.c
DRIVER_SOURCES += stm32f1xx_hal_rcc.c
DRIVER_SOURCES += stm32f1xx_hal_rtc_ex.c
DRIVER_SOURCES += stm32f1xx_hal_rtc.c
DRIVER_SOURCES += stm32f1xx_hal_sd.c
DRIVER_SOURCES += stm32f1xx_hal_smartcard.c
DRIVER_SOURCES += stm32f1xx_hal_spi_ex.c
DRIVER_SOURCES += stm32f1xx_hal_spi.c
DRIVER_SOURCES += stm32f1xx_hal_sram.c
DRIVER_SOURCES += stm32f1xx_hal_tim.c
#DRIVER_SOURCES += stm32f1xx_hal_timebase_rtc_alarm_template.c
#DRIVER_SOURCES += stm32f1xx_hal_timebase_tim_template.c
DRIVER_SOURCES += stm32f1xx_hal_uart.c
DRIVER_SOURCES += stm32f1xx_hal_usart.c
DRIVER_SOURCES += stm32f1xx_hal_wwdg.c
DRIVER_SOURCES += stm32f1xx_hal.c
DRIVER_SOURCES += stm32f1xx_ll_adc.c
DRIVER_SOURCES += stm32f1xx_ll_crc.c
DRIVER_SOURCES += stm32f1xx_ll_dac.c
DRIVER_SOURCES += stm32f1xx_ll_dma.c
DRIVER_SOURCES += stm32f1xx_ll_exti.c
DRIVER_SOURCES += stm32f1xx_ll_fsmc.c
DRIVER_SOURCES += stm32f1xx_ll_gpio.c
DRIVER_SOURCES += stm32f1xx_ll_i2c.c
DRIVER_SOURCES += stm32f1xx_ll_pwr.c
DRIVER_SOURCES += stm32f1xx_ll_rcc.c
DRIVER_SOURCES += stm32f1xx_ll_rtc.c
DRIVER_SOURCES += stm32f1xx_ll_sdmmc.c
DRIVER_SOURCES += stm32f1xx_ll_spi.c
DRIVER_SOURCES += stm32f1xx_ll_tim.c
DRIVER_SOURCES += stm32f1xx_ll_usart.c
DRIVER_SOURCES += stm32f1xx_ll_usb.c
DRIVER_SOURCES += stm32f1xx_ll_utils.c

#Include Header file
EXTRAINCDIRS += $(TOP)/driver/STM32F1xx_HAL_Driver/Inc \
$(TOP)/driver/STM32F1xx_HAL_Driver/Legacy/Inc

#include C source 
C_SOURCES += $(DRIVER_SOURCES)