###########################################################
# GCC template makefile
###########################################################

  	EDU_BOARD_SIMPLE_PWM_BASIC :=
  	EDU_BOARD_SIMPLE_PWM_BASIC += stm32f4xx_hal_msp.c
  	EDU_BOARD_SIMPLE_PWM_BASIC += stm32f4xx_it.c
  	EDU_BOARD_SIMPLE_PWM_BASIC += syscalls.c
  	EDU_BOARD_SIMPLE_PWM_BASIC += sysmem.c
  	EDU_BOARD_SIMPLE_PWM_BASIC += system_stm32f4xx.c
  	EDU_BOARD_SIMPLE_PWM_BASIC += CLCD.c
  	EDU_BOARD_SIMPLE_PWM_BASIC += 7SEG.c
    EDU_BOARD_SIMPLE_PWM_BASIC += main.c


    EXTRAINCDIRS += $(TOP)/StudyCode/M-HIVE-EduBoard/cubeMXstudy/09_PWM_Basic/Inc

    ASM_SOURCES += $(DEFAULT_ASMSOURCES)

    C_SOURCES += $(EDU_BOARD_SIMPLE_PWM_BASIC)
